#!/usr/bin/env bash
# displays numbers from 1 to 100.

c=1
while [ $c -lt 101 ]
do
    if [ $((c%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((c%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$c"
    fi
    ((c++))
done
