#!/usr/bin/env bash
#iterates through a loop and displays a different text for i4 and for i8 and the same text for others

print="Best school"
c=0

while [ $c -lt 10 ]
do
	if [ $c = 3 ]
	then
		echo "bad luck"
	elif [ $c = 7 ]
	then
		echo "good luck"
	else
		echo "$print"
	fi
	((c++))
done
